tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#703722",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "on-secondary-fixed": "#1b1c1c",
        outline: "#767870",
        "primary-fixed": "#dce6cf",
        "surface-tint": "#58614f",
        "primary-container": "#5a6351",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#474747",
        "on-secondary-container": "#656464",
        "secondary-container": "#e4e2e1",
        "on-tertiary-fixed": "#380d00",
        "tertiary-fixed": "#ffdbcf",
        "on-tertiary": "#ffffff",
        "on-surface": "#1a1c1b",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        primary: "#424b3a",
        "surface-dim": "#dadad8",
        "inverse-primary": "#c0cab4",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf9f7",
        surface: "#faf9f7",
        "on-background": "#1a1c1b",
        "primary-fixed-dim": "#c0cab4",
        tertiary: "#713823",
        "surface-container-low": "#f4f3f1",
        "outline-variant": "#c6c7be",
        background: "#faf9f7",
        "surface-variant": "#e3e2e0",
        "surface-container-highest": "#e3e2e0",
        "inverse-surface": "#2f3130",
        secondary: "#5f5e5e",
        "secondary-fixed": "#e4e2e1",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#414939",
        "on-tertiary-container": "#ffd1c2",
        "secondary-fixed-dim": "#c8c6c6",
        "on-surface-variant": "#454841",
        "surface-container-high": "#e9e8e6",
        "tertiary-container": "#8e4f38",
        "on-primary-fixed": "#161e10",
        "on-primary-container": "#d5dfc8",
        "surface-container": "#efeeec",
        "inverse-on-surface": "#f1f1ef",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
